
---
- hosts: localhost
    


  tasks:
         - name: Install apache
           yum: pkg=httpd state=latest
           notify: restart apache

         - name: Start Apache Service
           service: name=httpd state=restarted

         - name: Copy Index File to host a sample website
           copy: src=/root/TestGitRepo/index.html dest=/var/www/html/

  handlers:
         - name: restart apache
           service: name=httpd state=restarted
